"""initial

Revision ID: 0001_initial
Revises:
Create Date: 2026-06-16 16:21:17.796320
"""
import sqlalchemy as sa
from alembic import op

revision = "0001_initial"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "action_log",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("delivery_id", sa.Text(), nullable=True),
        sa.Column("connection_id", sa.Text(), nullable=True),
        sa.Column("action", sa.Text(), nullable=False),
        sa.Column("ok", sa.Boolean(), nullable=False),
        sa.Column("detail", sa.Text(), nullable=True),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "connections",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("external_id", sa.Text(), nullable=False),
        sa.Column("display_name", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("access_token_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("refresh_token_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("token_expires_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("cp_api_key_ciphertext", sa.LargeBinary(), nullable=True),
        sa.Column("scopes", sa.Text(), server_default="", nullable=False),
        sa.Column("connection_metadata", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("tenant_id", "provider", "external_id", name="uq_conn_identity"),
    )
    op.create_index(
        "ix_conn_tenant_provider", "connections", ["tenant_id", "provider"], unique=False
    )
    op.create_table(
        "webhook_events",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("provider", sa.Text(), nullable=False),
        sa.Column("external_delivery_id", sa.Text(), nullable=False),
        sa.Column("payload_digest", sa.Text(), nullable=False),
        sa.Column("received_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("processed_at", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("result", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "external_delivery_id", name="uq_webhook_delivery"),
    )
    op.create_table(
        "container_bindings",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("connection_id", sa.Text(), nullable=False),
        sa.Column("container_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("resource_filters", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_binding_container", "container_bindings", ["container_id"], unique=False)
    op.create_table(
        "deliveries",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("task_id", sa.Text(), nullable=False),
        sa.Column("container_id", sa.Text(), nullable=False),
        sa.Column("connection_id", sa.Text(), nullable=False),
        sa.Column("origin_ref", sa.JSON(), nullable=False),
        sa.Column("provider_message_handle", sa.JSON(), nullable=True),
        sa.Column("surface", sa.JSON(), server_default='["reasoning","result"]', nullable=False),
        sa.Column("last_seq", sa.Integer(), server_default="0", nullable=False),
        sa.Column("state", sa.Text(), server_default="streaming", nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"]),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("task_id"),
    )
    op.create_table(
        "routing_rules",
        sa.Column("id", sa.Text(), nullable=False),
        sa.Column("connection_id", sa.Text(), nullable=False),
        sa.Column("tenant_id", sa.Text(), nullable=False),
        sa.Column("priority", sa.Integer(), server_default="100", nullable=False),
        sa.Column("match", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("target", sa.JSON(), server_default="{}", nullable=False),
        sa.Column("input_template", sa.Text(), server_default="{{ text }}", nullable=False),
        sa.Column("surface", sa.JSON(), server_default='["reasoning","result"]', nullable=False),
        sa.Column("enabled", sa.Boolean(), server_default=sa.text("true"), nullable=False),
        sa.Column("created_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.Column("updated_at", sa.TIMESTAMP(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["connection_id"], ["connections.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_rule_conn_enabled",
        "routing_rules",
        ["connection_id", "enabled", "priority"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rule_conn_enabled", table_name="routing_rules")
    op.drop_table("routing_rules")
    op.drop_table("deliveries")
    op.drop_index("ix_binding_container", table_name="container_bindings")
    op.drop_table("container_bindings")
    op.drop_table("webhook_events")
    op.drop_index("ix_conn_tenant_provider", table_name="connections")
    op.drop_table("connections")
    op.drop_table("action_log")
    # ### end Alembic commands ###
